### ISSUE TITLE
_isEnabledOnRevisit attribute

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-trickle#12]
Can we setup trickle so it makes use of an_isEnabledOnRevisit attribute to determine whether a views children should be relocked, even when completed?

In the case of an assessment with multiple attempts of the article, we would want the user to have the same functionality each time they access this, something which trickle doesn't currently seem to offer. By using an attribute as mentioned above we would be able to define how the locking works so it is either only locked until complete (as default) or locked each time. Would mean it wouldn't just be limited to work this way for assessments only.

**Comment by LukaszGrela** [comment]
+1

**Comment by oliverfoster** [comment]
old, redundant
