### ISSUE TITLE
On iPhone after submitting input data trickle doesn't gets enable.

### ISSUE THREAD

**Issue by ramjeet-getSolutions** [adaptlearning/adapt-contrib-trickle#132]
After entering text in input field then click on submit button activity gets completed but trickle doesn't gets enable. if we scroll up and then scroll down works fine then. Its ios device specific issue. It can be replicated in ipad as well.

**Comment by oliverfoster** [comment]
Please specify the version you're using.

**Comment by ramjeet-getSolutions** [comment]
Its happening on latest version which is 5.2.1.

**Comment by oliverfoster** [comment]
cannot reproduce in ios 14.7.1 with adapt_framework 5.17.0, core 6.0.0, trickle 5.2.1 and text input 4.2.0
