### ISSUE TITLE
Trickle Button sometimes being saved to SCORM

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt-contrib-trickle#146]
One of my client's courses has been having issues retrieving course state with Spoor. With errors being raised with certain `_trackingIds`.

The error message shared below shows the errors with Tracking Ids as well as Adapt trying to find a `trickle-x` component. I believe Spoor may be saving these components.

![image](https://user-images.githubusercontent.com/1676635/159004610-61461e1a-24b3-4187-8d60-999cc4084d4c.png)

The course uses Trickle Button on every block. When Trickle is removed from the blocks with the erronous tracking blocks the Spoor extension works again.

FW v5.15.2
Trickle v5.2.5
Spoor v3.10.1

**Comment by joe-allen-89** [comment]
Have you recently updated the trickle/spoor plugin? And have you run a force rebuild. Looking at other PRs this appears to have been raised in previous versions. I have been unable to replicate using these versions.

**Comment by simondate** [comment]
This was from an Authoring Tool course where you aren't able to manually reset the tracking-ids with a grunt command.

Does exporting and reimporting the course reset them?

**Comment by joe-allen-89** [comment]
If you could go into the course and rather than preview hit force rebuild before publishing/testing.

**Comment by simondate** [comment]
The client just decided to remove Trickle from the components. I have since been unable to replicate this.
