### ISSUE TITLE
Trickle not allowing course to continue without requiring completion of an article

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt-contrib-trickle#155]
**Description**
Trickle does not allow you to continue the course until you have completed the previous question, instead when clicking the 'continue' button it does nothing. 

**Additional Information**
I can see the following error in the console when this issue occurs:
<img width="851" alt="trickle error" src="https://user-images.githubusercontent.com/61159216/170059236-f0d7ec86-0edc-4781-9b4b-9760e0d43c9b.png">

**Steps to replicate:**

1. Create a course with a question component, e.g. multiple choice question component
2. Add the trickle extension and ensure it is enabled
3. In the article that holds the multiple choice question component, enable trickle and ensure the trickle settings for the article are configured as in the screenshots below, most importantly ensure that the '**button attributes**' is enabled and the '**Initial visibility**' is set to '**visible**' and the '**Step Locking Attributes**' is enabled and the '**Completion Required**' property is set to false:
<img width="831" alt="trickle 1" src="https://user-images.githubusercontent.com/61159216/170057755-7bae71c0-cfcd-46ec-b280-a642f4baa61f.png">
<img width="762" alt="trickle 2" src="https://user-images.githubusercontent.com/61159216/170057769-a797a13b-c90a-4699-a5ca-e82c7cd61aad.png">
<img width="823" alt="trickle 3" src="https://user-images.githubusercontent.com/61159216/170057782-562963ac-2ead-46d6-94c5-c4f83fa86fd0.png">
<img width="800" alt="trickle 4" src="https://user-images.githubusercontent.com/61159216/170057787-529298a8-f878-49d2-81e0-2ae948734d96.png">
<img width="811" alt="trickle 5" src="https://user-images.githubusercontent.com/61159216/170057799-dc02a26d-d019-43f1-b64b-4fb32570892e.png">
<img width="357" alt="trickle 6" src="https://user-images.githubusercontent.com/61159216/170057814-6f21efc6-688a-4302-a33c-134401ffcc19.png">

**Expected results**
With 'Completion Required' disabled, when the continue is clicked it should allow the user to move on.

 **Actual results**
Clicking the button does not allow the user to move on, they just get a blank screen like it was the end of the course.

**Comment by ethan-lp** [comment]
N.B. this has been replicated with fw 5.19.3
