### ISSUE TITLE
Trickle should all disable at course level (for testing etc)

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt-contrib-trickle#160]
For writing courses that include trickle, it would be beneficial to be able to toggle the extension on/off at course level. Much like many other extensions

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-trickle/blob/59ba15f8fc6632e68d1f25803a0162ec629c87b3/js/controller.js#L50

```js
if (Adapt.course.get('_trickle')?._isEnabled === false) return;
```
