### ISSUE TITLE
Not showing next article after completed assessment article

### ISSUE THREAD

**Issue by mmitic86** [adaptlearning/adapt-contrib-trickle#176]
If banks are enabled in assessment and trickle is applied on assessment article it will not show/render next article. Based on my testing it starts doing this from version 5.0.0.

**Comment by oliverfoster** [comment]
The vanilla course works like this. The second article contains the results component.

**Comment by oliverfoster** [comment]
No response

**Comment by mmitic86** [comment]
Sorry for no response. The bug was in our custom Assessment extension.
