### ISSUE TITLE
No longer working at article level after block slider

### ISSUE THREAD

**Issue by fosterc1** [adaptlearning/adapt-contrib-trickle#177]
Previously Trickle would work after completing all blocks in the current article using block slider

### Your environment
* version (AT v11.1 / FW v5.24.0)
* Chrome Version 108.0.5359.94
* Macbook 

### Steps to reproduce
Enable Trickle within the Article, enable scroll automatically, after previewing complete all blocks/components with the article.

### Expected behaviour
After completion of blocks, the continue button to be shown

### Actual behaviour
The continue button is no longer show, but the next block, without any styling is shown.

### Screenshots (if you can)

![2022-12-07_13-19-43](https://user-images.githubusercontent.com/29701150/206189778-a92ad222-8d4d-490c-b41a-d2747b40a701.png)
![2022-12-07_13-19-17](https://user-images.githubusercontent.com/29701150/206189795-8dd04efd-19fd-448b-8f2c-b32010bdfe1c.png)

**Comment by oliverfoster** [comment]
Could I have the plugin versions as well please? Trickle and blockslider.

**Comment by fosterc1** [comment]
Hello

This now seems to be working again with:
Trickle 6.4.2
Article Block Slider 3.1.1

Thanks
