### ISSUE TITLE
`_logState` not implemented

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-trickle#194]
https://github.com/adaptlearning/adapt-contrib-trickle/commit/426c583e55f7b7fa331f944b75bc47d942d50e00 added a feature to control whether the state is included in the log. The schemas and example.json include the attribute, but it doesn't look like it is actually used in the code.

I assume https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/models.js#L325 should account for this attribute?

**Comment by oliverfoster** [comment]
Yeas, exactly.
