### ISSUE TITLE
First model remains `_isLocked` when content order is randomised

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-trickle#223]
Since https://github.com/adaptlearning/adapt-contrib-trickle/releases/tag/v5.1.0, if page content is randomised (e.g. via an assessment) and the first component displayed isn't the first in the natural model structure order, that component remains `_isLocked` for the remainder of the course session.  The model therefore appears locked in the pageLevelProgress despite trickle itself unlocking to the next model. All subsequent models work as expected.

**Comment by oliverfoster** [comment]
I have a feeling it's just that the locks aren't recalculated after the assessment reworks its children.

**Comment by danielghost** [comment]
`applyLocks` does seem to be called following an assessment amending the children. Turns out this is actually the same issue as https://github.com/adaptlearning/adapt-contrib-trickle/issues/164. The example code in https://github.com/adaptlearning/adapt-contrib-trickle/issues/164#issuecomment-1499359933 seems to resolve the issue. I will create a PR for review.

**Comment by oliverfoster** [comment]
That makes sense.
