### ISSUE TITLE
Pages with single blocks in articles prevents trickle working correctly

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt-contrib-trickle#24]
For pages with multiple articles that have only one block the following line prevent progression past non trickle articles/blocks that need interaction to complete. 

https://github.com/adaptlearning/adapt-contrib-trickle/blob/develop/js/adapt-contrib-trickle.js#L128

Trickle button is not shown for completion of these articles/blocks.

**Comment by zenduo** [comment]
Moved here https://adaptlearning.atlassian.net/browse/ABU-480
