### ISSUE TITLE
Locking assumptions

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-trickle#30]
It seems as though trickle makes some assumptions that a page with articles set to trickle should apply locking to all articles rather than just those which have the object.

For example a page with three articles a-05, a-10, a-15 of which only a-05 has a _trickle object, correctly locks a-10 and a-15 until a-05 is completed. However on the completion of a-05 it only unlocks a-10 rather than including a-15 also. Currently once a-10 is completed, a-15 shows without the trickle button being displayed as it was for a-05 but I would only expect articles which have the _trickle object to require completion before unlocking the next article.

**Comment by taylortom** [comment]
I have also replicated odd behaviour with the following config:
- Multiple articles on a page.
- Trickle enabled on any article other than the first.
- Completing the first article causes the button to appear. Clicking the button makes the next article appear, despite the fact that the required criteria for locking haven't been met (e.g. a-05 completed, so a-15 is unlocked without completing a-10).

**Comment by LukaszGrela** [comment]
As @taylortom mentioned I was also affected by this issue, the only difference that in my "setup" it starts with the trickle button visible. 

Following function:

            blockSetToComplete: function(block) {
                console.log("blockSetToComplete(block="+block.get('_id')+")");
                // Index here is plus one
                if (this.trickleCurrentIndex == this.pageElements.length) {
                    return;
                }
                if  (this.pageElements[this.trickleCurrentIndex-1].get('_trickle')){
                    this.showTrickle();
                } else if (this.pageElements[this.trickleCurrentIndex].get('_trickle')){
                    this.showTrickle();
                } else if (!this.pageElements[this.trickleCurrentIndex].get('_trickle')) {
                    this.setItemToVisible(this.pageElements[this.trickleCurrentIndex]);
                }
            },

seems to dont care which block was set to complete - maybe it should check this? e.g. if it is the current block or anyone before?

**Comment by taylortom** [comment]
That's great, thanks @LukaszGrela :) 
If you could submit a pull request, someone will have a look at this asap.

**Comment by LukaszGrela** [comment]
with pleasure but don't know how:)

**Comment by oliverfoster** [comment]
redundant
