### ISSUE TITLE
Position of the trickle button covers some content

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt-contrib-trickle#32]
At the moment the trickle button is placed at bottom of the last visible container, this can cause the issue that the trickle button will cover the content of that container (e.g. block). Can the trickle be positioned at the top of the next (invisible) container? This way the padding between containers will give the breathing space between content and trickle button.

**Comment by LukaszGrela** [comment]
It is placed at the bottom of the browser:) but could it add padding to the body when visible? I'll try with it later, maybe it will work.

**Comment by oliverfoster** [comment]
The body or the #wrapper element should work. The height of the button + 20pxish.

**Comment by LukaszGrela** [comment]
Yes, I thought of body as it will always be there and usually without any style (padding) added.

**Comment by zenduo** [comment]
Can this one be closed now? Works well in develop branch.

**Comment by oliverfoster** [comment]
The pr for this went in last week. Good to close.
