### ISSUE TITLE
adapt-contrib-trickle is shrinking images in the narrative component

### ISSUE THREAD

**Issue by mes333** [adaptlearning/adapt-contrib-trickle#33]
Hi I am having an issue with adapt-contrib-trickle it is shrinking images in the narrative component until I press the continue button to go to the next block. Then the narrative component images return to normal. Not sure why.

**Comment by oliverfoster** [comment]
Hi mes33. This is a known and slightly complicated issue. Trickle sets the hidden components as display:none, which leaves them with no height or width. The narrative component manually sets it's image / image container relative to it's own height and width. The only way to change this behavior at present is to force the narrative to think the window has resized at the point when trickle makes it visible. Triggering an Adapt.trigger("device:resize") event, or even sometimes a $(window).resize() is usually enough. We'd welcome a PR on the matter if you can find time?

**Comment by LukaszGrela** [comment]
I can confirm that placing the `Adapt.trigger(;device:resize');` in the `showItem` method works


            showItem: function(model) {
                $('.' + model.get('_id')).removeClass('trickle-hidden');
                Adapt.trigger('device:screenSize', Adapt.device.screenWidth);
                Adapt.trigger('device:resize');
            },

**Comment by mes333** [comment]
Thanks so much LukaszGrela that did the trick! Good find :)

**Comment by oliverfoster** [comment]
Cool *high fives*
