### ISSUE TITLE
_isCourseComplete is false however course is set to complete in the LMS

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt-contrib-trickle#35]
Why the `_isCourseComplete` is false?

`{"spoor":{"completion":"11111111111","_isCourseComplete":false,"_isAssessmentPassed":false}}`

the config.json

    "_spoor": {
        "_tracking": {
            "_requireCourseCompleted": true,
            "_requireAssessmentPassed": false,
            "_shouldSubmitScore": false
        },
        "_reporting": {
            "_comment": "Your options here are 'completed', 'passed', 'failed', and 'incomplete'",
            "_onTrackingCriteriaMet": "completed",
            "_onAssessmentFailure": "incomplete"
        }
    }

**Comment by oliverfoster** [comment]
old, incorrect repo
