### ISSUE TITLE
Completed components locked in trickle on revisit

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt-contrib-trickle#57]
when you have presentational components loaded from Spoor (you have left the course and come back), some of the components have been locked off by trickle, despite having been completed. Reported by @andrewhosgood 

This is because trickle uses _isInteractionComplete for completion attribute by default. Can set _completionAttribute in config.json : "_trickle": { "_completionAttribute": "_isComplete" }

Needs documenting in readme, exampe.json and properties.schema if this is to be used as a solution.

**Comment by belal-almassri-spongeuk** [comment]
I suggest making PR for the config page including the following line of code: 
"_trickle": { "_completionAttribute": "_isInteractionComplete " }.

I know it is set by default, but it could be handy to have it in the config page as well.

**Comment by dancgray** [comment]
Issue created in Jira:
https://adaptlearning.atlassian.net/browse/ABU-1127

I think there is a bug with this when _completionAttribute =  _isInteractionComplete. See jira ticket:
https://adaptlearning.atlassian.net/browse/ABU-1126

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#875
