### ISSUE TITLE
Cannot disable trickle on articles after using a custom _completionAttribute

### ISSUE THREAD

**Issue by andrewhosgood** [adaptlearning/adapt-contrib-trickle#58]
When you set the attribute in `config.json` e.g.

```json
"_trickle": {
    "_completionAttribute": "_isComplete"
}
```

Then disabling trickle in articles with:

```json
"_trickle": {
    "_isEnabled": false
}
```

doesn't appear to work.

Removing the `_completionAttribute` again works.

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#876
