### ISSUE TITLE
Trickle height is not properly restricted on load

### ISSUE THREAD

**Issue by andrewhosgood** [adaptlearning/adapt-contrib-trickle#60]
1. Create a new adapt course
2. On the demo theme with Vanilla, go to the assessment: co-15 (`http://localhost:9001/#/id/co-15`)
3. **Height of page is wrong**
4. Open and close one of the sidebars (resources or PLP) and close
5. Height is now fixed

**Comment by samumist** [comment]
I confirm. when open and close the drawer (sidebar) does fix the page height problem.

**Comment by samumist** [comment]
update:
Open then close drawer does seem to fix the page height problem on desktop (mac chrome), but not on mobile (android chrome).

**Comment by andrewhosgood** [comment]
Fixed with https://github.com/adaptlearning/adapt_framework/pull/797

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#877
