### ISSUE TITLE
trickle-buttonPlugin.js#shouldRenderButton - invalid if statement, missing brackets

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt-contrib-trickle#62]
The if statement with 
`            if (!trickleConfig._button._component == "trickle-button") return false;`

will always be false, it should be:
`            if (!(trickleConfig._button._component == "trickle-button")) return false;`

or
`            if (trickleConfig._button._component !== "trickle-button") return false;`

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#879
